version: "3"
services: 
        node-app:
                build: .
                ports:
                        - "3000:3000"
                volumes:
                        - ./:/app:ro
                        - /app/node_modules
                environment:
                        - PORT=3000
                        - MONGO_USER=saty
                        - MONGO_USER1=9874721446
                        - SESSION_SECRET=secret  
                depends_on:
                        - mongo
                           
        mongo:
                image: mongo:latest
                environment:
                        - MONGO_INITDB_ROOT_USERNAME=saty
                        - MONGO_INITDB_ROOT_PASSWORD=9874721446
                        
                volumes:
                        - mongo-db:/data/db

        redis:
                image: redis




volumes:
        mongo-db:        
                        
                                
